/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VoteChainIndia } from "./VoteChainIndia";
export * as factories from "./factories";
export { VoteChainIndia__factory } from "./factories/VoteChainIndia__factory";
